from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field
import google.generativeai as genai

from dotenv import load_dotenv
from .config_utils import get_gemini_api_key

load_dotenv()

router = APIRouter()

class TitleRequest(BaseModel):
    """Request schema for generating a chat title."""
    prompt: str = Field(..., description="The first user prompt of the chat")


# PUBLIC_INTERFACE
@router.post(
    "/chat/title",
    response_model=str,
    summary="Generate a chat title from first prompt",
    description="Given the first user prompt, generate a concise chat history title using Gemini. Returns only the resulting title string.",
    responses={
        400: {"description": "Blank or invalid input"},
        500: {"description": "Gemini error or misconfiguration"},
    },
    tags=["Chat"]
)
async def generate_title(request: TitleRequest) -> str:
    """
    PUBLIC_INTERFACE
    Generate a concise, human-readable chat title using the Gemini API, based on the first user message.

    Args:
        request (TitleRequest): The first prompt/message of the chat.

    Returns:
        str: Concise chat title generated by Gemini.

    Raises:
        HTTPException: If input is blank/invalid or Gemini fails.
    """
    prompt = (request.prompt or "").strip()
    if not prompt:
        raise HTTPException(status_code=400, detail="Prompt is required and cannot be blank.")
    gemini_api_key = get_gemini_api_key()
    if not gemini_api_key:
        raise HTTPException(status_code=500, detail="Gemini API key not set in environment.")

    instruction = (
        "Given the following user message, generate a 3 to 8-word title that could be used to label the conversation in a chat history sidebar. "
        "Make it succinct, use plain language, and do not use quotes or punctuation. "
        "Do NOT include the user's full text or copy the prompt verbatim. "
        "Focus on the main topic or intent of the message."
    )

    try:
        genai.configure(api_key=gemini_api_key)
        model = genai.GenerativeModel("gemini-2.5-flash")
        content = f"{instruction}\n\nUser's message: {prompt}"
        response = model.generate_content([{"role": "user", "parts": [content]}])
        title = response.text.strip()
        # Clean up output: remove extra punctuation/quotes, ensure single line
        import re
        title = re.sub(r"^[\"'`]+|[\"'`]+$", "", title)
        title = title.replace("\n", " ").replace("\r", " ")
        if not title or len(title) < 3:
            raise ValueError("Gemini did not return a valid title")
        return title
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to generate title with Gemini: {e}")
