# ==============================================================================
# IMPORTANT: This backend requires the following environment variable to function:
#   - GEMINI_API_KEY : Your Google Gemini API key
# Make sure to create a `.env` file or provide GEMINI_API_KEY at deployment.
# Without this, POST /chat will return a 500 Internal Server Error.
# ==============================================================================

import os
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from typing import List
import google.generativeai as genai

from dotenv import load_dotenv
from langchain.memory import ConversationBufferMemory

# Load environment variables
load_dotenv()

# Memory store for chat contexts (keyed by session_id).
CONVERSATION_MEMORY = {}

app = FastAPI(
    title="IntelliQuery Chatbot API",
    version="1.0.0",
    description="FastAPI backend for the IntelliQuery chatbot, providing chat endpoints using RAG from answers.txt, Google Gemini API, and context tracking."
)

openapi_tags = [
    {"name": "Health", "description": "Health check endpoint."},
    {"name": "Chat", "description": "Endpoints for chat, response retrieval, and context management."}
]

# Allow CORS from everywhere for demo/dev
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class ChatRequest(BaseModel):
    """Schema for a chat request."""
    session_id: str = Field(..., description="Unique session identifier for the conversation context.")
    query: str = Field(..., description="User's query (question or message).")

class ChatResponse(BaseModel):
    """Schema for the chat response."""
    rag_answer: str = Field(..., description="Retrieved answer from the RAG knowledge base.")
    gemini_answer: str = Field(..., description="Enhanced answer generated by Gemini API.")
    conversation_history: List[dict] = Field(..., description="Full chat context for this session.")

def load_answers(filepath: str) -> List[dict]:
    """Load questions and answers from the answers.txt file as a list of dicts ([{'q': ..., 'a': ...}, ...])."""
    qa_list = []
    with open(filepath, encoding='utf-8') as f:
        lines = f.readlines()
    q, a = None, None
    for line in lines:
        line = line.strip()
        if line.startswith("Q:"):
            q = line[2:].strip()
        elif line.startswith("A:"):
            a = line[2:].strip()
            if q is not None and a is not None:
                qa_list.append({'q': q, 'a': a})
                q, a = None, None
    return qa_list

def similarity(a: str, b: str) -> float:
    """Simple similarity score based on token overlap (lower resource fallback for semantic matching)."""
    set_a, set_b = set(a.lower().split()), set(b.lower().split())
    shared = set_a.intersection(set_b)
    if not set_a or not set_b:
        return 0.0
    return len(shared) / max(len(set_a), len(set_b))

def rag_retrieve(query: str, qa_list: List[dict], threshold: float = 0.38) -> dict:
    """
    Retrieve the QA pair most relevant to the query based on similarity.
    If similarity is below the threshold, treat as no relevant information.
    """
    if not qa_list:
        return {"q": "", "a": ""}
    best_match = max(qa_list, key=lambda qa: similarity(query, qa['q']))
    sim_score = similarity(query, best_match['q'])
    if sim_score < threshold:
        return {"q": "", "a": ""}
    return best_match

def get_gemini_response(query: str, rag_answer: str, memory: ConversationBufferMemory) -> str:
    """
    PUBLIC_INTERFACE
    Enhance the RAG answer using Google Gemini API, considering the chat context.
    """
    # Prepare the prompt
    mem_str = memory.buffer_as_str if hasattr(memory, "buffer_as_str") else ""
    prompt = (
        f"You are an expert software assistant. The user asked: '{query}'\n"
        f"Most relevant knowledge base answer: \"{rag_answer}\"\n"
        f"Conversation context: {mem_str}\n"
        f"Please provide the clearest and most helpful answer based on all of the above."
    )

    # Call Gemini API
    gemini_api_key = os.getenv("GEMINI_API_KEY", "")
    if not gemini_api_key:
        raise HTTPException(status_code=500, detail="Gemini API key is not set in environment variables.")
    try:
        genai.configure(api_key=gemini_api_key)
        # Changed model name from 'gemini-pro' to 'gemini-2.5-flash'
        model = genai.GenerativeModel("gemini-2.5-flash")
        response = model.generate_content([{"role": "user", "parts": [prompt]}])
        answer = response.text.strip()
        return answer
    except Exception as e:
        # Fallback to original RAG answer if Gemini API fails
        return f"[Gemini enhancement unavailable: {e}]\nKnowledge base answer: {rag_answer}"

# Load the knowledge base at startup
ANSWERS_PATH = os.path.join(os.path.dirname(__file__), "answers.txt")
QA_LIST = load_answers(ANSWERS_PATH)

@app.get("/", tags=["Health"])
def health_check():
    """
    PUBLIC_INTERFACE
    API health check endpoint.

    Returns:
        dict: Status message.
    """
    return {"message": "Healthy"}

@app.post("/chat", response_model=ChatResponse, tags=["Chat"], summary="Chat with bot", description="Submit a chat query. Retrieves an answer from the RAG knowledge base, enhances with Gemini, and returns the chat context.")
def chat(request: ChatRequest):
    """
    PUBLIC_INTERFACE
    Handles a user's chat request, uses RAG to get initial answer, calls Gemini API for enhanced answer,
    and maintains conversation context using ConversationBufferMemory.

    Args:
        request (ChatRequest): Contains session_id and user query.
    Returns:
        ChatResponse: RAG answer, Gemini-enhanced answer, and conversation context.
    """
    import traceback

    try:
        # Handle conversation memory
        session_id = request.session_id
        if not session_id or not isinstance(session_id, str):
            raise HTTPException(status_code=400, detail="session_id must be a non-empty string.")

        if session_id not in CONVERSATION_MEMORY:
            # Set output_key explicitly to resolve ambiguous/missing output key issues when saving context
            CONVERSATION_MEMORY[session_id] = ConversationBufferMemory(
                return_messages=True,
                output_key="output"
            )
        memory = CONVERSATION_MEMORY[session_id]

        # Utility to always ensure output passed to memory is a non-None string
        def _safe_str_output(val, fallback="No answer available"):
            if val is None or (isinstance(val, str) and val.strip() == ""):
                return fallback
            return str(val)

        # Add user input to memory with output_key structure always present
        try:
            # For initial user message, output is set to a default response (to avoid None)
            memory.save_context({"input": request.query}, {"output": _safe_str_output("", "No answer available")})
        except Exception as e:
            raise HTTPException(status_code=500, detail=f"Failed to save user context: {e}")

        # RAG: Retrieve best match using threshold-based retrieval
        try:
            qa = rag_retrieve(request.query, QA_LIST)
            if qa.get("a", "") == "":
                # No relevant information found
                rag_answer = "No relevant information is present in the knowledge base."
                # Gemini answer should echo this message
                gemini_answer = "No relevant information is present in the knowledge base."
                # Add both to memory to maintain consistent history
                memory.save_context({"input": request.query}, {"output": rag_answer})
                memory.save_context({"input": request.query}, {"output": gemini_answer})
                conversation_history = []
                if hasattr(memory, "chat_memory") and hasattr(memory.chat_memory, "messages"):
                    for m in memory.chat_memory.messages[-20:]:
                        m_dict = {}
                        if hasattr(m, "type") and hasattr(m, "content"):
                            m_dict = {"type": m.type, "content": _safe_str_output(m.content)}
                        conversation_history.append(m_dict)
                return ChatResponse(
                    rag_answer=rag_answer,
                    gemini_answer=gemini_answer,
                    conversation_history=conversation_history,
                )
            else:
                rag_answer = _safe_str_output(qa.get("a", None))
        except Exception:
            rag_answer = "No relevant information is present in the knowledge base."
            gemini_answer = "No relevant information is present in the knowledge base."
            memory.save_context({"input": request.query}, {"output": rag_answer})
            memory.save_context({"input": request.query}, {"output": gemini_answer})
            conversation_history = []
            if hasattr(memory, "chat_memory") and hasattr(memory.chat_memory, "messages"):
                for m in memory.chat_memory.messages[-20:]:
                    m_dict = {}
                    if hasattr(m, "type") and hasattr(m, "content"):
                        m_dict = {"type": m.type, "content": _safe_str_output(m.content)}
                    conversation_history.append(m_dict)
            return ChatResponse(
                rag_answer=rag_answer,
                gemini_answer=gemini_answer,
                conversation_history=conversation_history,
            )

        # Add bot's answer to memory before Gemini call, always use {"input": <prev_user>, "output": ...}
        try:
            # For consistency, always provide non-empty input with 'input' key for every save_context call
            memory.save_context({"input": request.query}, {"output": _safe_str_output(rag_answer)})
        except Exception as e:
            raise HTTPException(status_code=500, detail=f"Failed to save RAG answer to memory: {e}")

        # Enhance answer with Gemini
        try:
            gemini_answer = get_gemini_response(request.query, rag_answer, memory)
            gemini_answer = _safe_str_output(gemini_answer)
        except HTTPException:
            # Propagate Gemini API key missing explicitly
            raise
        except Exception as e:
            gemini_answer = _safe_str_output(f"[Gemini enhancement unavailable: {e}]\nKnowledge base answer: {rag_answer}")

        # Add Gemini-enhanced answer to memory, always use {"input": <prev_user>, "output": ...}
        try:
            memory.save_context({"input": request.query}, {"output": _safe_str_output(gemini_answer)})
        except Exception as e:
            # Compose a warning but do not crash the whole chat
            gemini_answer += f"\n[Warning: Failed to save Gemini response to memory: {e}]"

        # Prepare conversation history (latest 20 exchanges)
        conversation_history = []
        if hasattr(memory, "chat_memory") and hasattr(memory.chat_memory, "messages"):
            for m in memory.chat_memory.messages[-20:]:
                m_dict = {}
                if hasattr(m, "type") and hasattr(m, "content"):
                    # Ensure conversation history never exposes None as content
                    m_dict = {"type": m.type, "content": _safe_str_output(m.content)}
                conversation_history.append(m_dict)

        return ChatResponse(
            rag_answer=_safe_str_output(rag_answer),
            gemini_answer=_safe_str_output(gemini_answer),
            conversation_history=conversation_history,
        )
    except HTTPException:
        raise  # Allow FastAPI HTTPExceptions to propagate
    except Exception as e:
        # Log details for debugging
        tb = traceback.format_exc()
        print(f"Internal Server Error in /chat endpoint: {e}\nTraceback:\n{tb}")
        raise HTTPException(status_code=500, detail=f"Internal Server Error: {e}")


# Add endpoint doc for WebSocket and real-time (optional, can expand later)
@app.get("/chat/wsinfo", tags=["Chat"], summary="WebSocket usage info", description="Info about WebSocket/API support for real-time chat.")
def chat_wsinfo():
    """
    PUBLIC_INTERFACE
    Returns information about real-time chat support (WebSocket or usual polling).
    """
    return {"detail": "Current version supports REST API chat only. Real-time WebSocket may be added in future versions."}
