# ==============================================================================
# IMPORTANT: This backend requires the following environment variables to function:
#   - REACT_APP_GEMINI_API_KEY (preferred) or GEMINI_API_KEY : Your Google Gemini API key
#   - REACT_APP_SUPABASE_DB_URL (preferred) or SUPABASE_DB_URL : Postgres connection string for Supabase (sslmode=require recommended)
# Make sure to create a `.env` file or provide these at deployment.
# Without a Supabase DB URL the app will not start (enforced in auth_utils).
# ==============================================================================

import os

from typing import List, Optional

from fastapi import FastAPI, HTTPException, Depends
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field, EmailStr
import google.generativeai as genai

from dotenv import load_dotenv
from langchain.memory import ConversationBufferMemory

# Import authentication/database helpers
from .auth_utils import (
    create_tables,
    get_db,
    create_user,
    get_user_by_username,
    verify_password,
    get_or_create_conversation,
    create_message,
    get_messages_for_session,
    get_conversations_for_user,
    attach_session_to_user,
)

# Import the chat title router
from .chat_title import router as chat_title_router

# Load environment variables
load_dotenv()

# Memory store for chat contexts (keyed by session_id). This augments DB history for quick context.
CONVERSATION_MEMORY: dict[str, ConversationBufferMemory] = {}

app = FastAPI(
    title="IntelliQuery Chatbot API",
    version="1.1.0",
    description="FastAPI backend for the IntelliQuery chatbot, providing chat endpoints using RAG from answers.txt, Google Gemini API, and context tracking. Supabase stores users, conversations, and messages.",
)

openapi_tags = [
    {"name": "Health", "description": "Health check endpoint."},
    {"name": "Chat", "description": "Endpoints for chat, history/title generation, response retrieval, and context management."},
    {"name": "UserAuth", "description": "Endpoints for user registration and login."},
]

# Register chat title router (Gemini-powered title generator)
app.include_router(chat_title_router)

# Allow CORS from everywhere for demo/dev
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


class ChatRequest(BaseModel):
    """Schema for a chat request."""
    session_id: str = Field(..., description="Unique session identifier for the conversation context.")
    query: str = Field(..., description="User's query (question or message).")


class ChatResponse(BaseModel):
    """Schema for the chat response."""
    rag_answer: str = Field(..., description="Retrieved answer from the RAG knowledge base.")
    gemini_answer: str = Field(..., description="Enhanced answer generated by Gemini API.")
    conversation_history: List[dict] = Field(..., description="Full chat context for this session.")


# --- AUTH SCHEMAS FOR REGISTRATION & LOGIN ---

class RegisterRequest(BaseModel):
    """Pydantic schema for user registration request."""
    username: str = Field(..., min_length=3, max_length=50, description="Unique username for registration")
    email: EmailStr = Field(..., description="User's email address")
    password: str = Field(..., min_length=6, max_length=128, description="User's password (plaintext, will be hashed)")


class RegisterResponse(BaseModel):
    """Schema for success/failure of registration."""
    id: int
    username: str
    email: EmailStr


class LoginRequest(BaseModel):
    """Pydantic schema for user login request."""
    username: str = Field(..., description="Registered username")
    password: str = Field(..., description="Password")


class LoginResponse(BaseModel):
    """Schema for login response."""
    id: int
    username: str
    email: EmailStr


class HistoryItem(BaseModel):
    """Schema for a single history message returned by history endpoint."""
    type: str = Field(..., description="Message type: 'human' or 'ai'")
    content: str = Field(..., description="Message text content")
    created_at: Optional[str] = Field(None, description="ISO timestamp of the message")


class ConversationInfo(BaseModel):
    """Schema representing minimal conversation metadata."""
    id: int = Field(..., description="Conversation id")
    session_id: str = Field(..., description="Conversation session id")
    title: Optional[str] = Field(None, description="Conversation title")
    created_at: Optional[str] = Field(None, description="Conversation creation timestamp (ISO)")


class AttachSessionRequest(BaseModel):
    """Schema to attach a session to a user (bind conversation to account)."""
    session_id: str = Field(..., description="Session to bind")
    username: str = Field(..., description="Username to bind the session to")
    title: Optional[str] = Field(None, description="Optional title to set if not already set")


def load_answers(filepath: str) -> List[dict]:
    """Load questions and answers from the answers.txt file as a list of dicts ([{'q': ..., 'a': ...}, ...])."""
    qa_list = []
    with open(filepath, encoding='utf-8') as f:
        lines = f.readlines()
    q, a = None, None
    for line in lines:
        line = line.strip()
        if line.startswith("Q:"):
            q = line[2:].strip()
        elif line.startswith("A:"):
            a = line[2:].strip()
            if q is not None and a is not None:
                qa_list.append({'q': q, 'a': a})
                q, a = None, None
    return qa_list


def similarity(a: str, b: str) -> float:
    """Simple similarity score based on token overlap (lower resource fallback for semantic matching)."""
    set_a, set_b = set(a.lower().split()), set(b.lower().split())
    shared = set_a.intersection(set_b)
    if not set_a or not set_b:
        return 0.0
    return len(shared) / max(len(set_a), len(set_b))


def rag_retrieve(query: str, qa_list: List[dict], threshold: float = 0.38, weak_threshold: float = 0.18) -> dict:
    """
    Retrieve the QA pair most relevant to the query based on similarity.
    Returns a dict with keys:
        - 'q': question string of best match (empty if none)
        - 'a': answer string of best match (empty if none)
        - 'weak_match': True if similarity is above weak_threshold but below main threshold, else False
    If similarity is below weak_threshold, treat as NO relevant information at all (not even general topic match).
    If similarity is above weak_threshold but below threshold, treat as GENERAL TOPIC match.
    If similarity is above threshold, treat as STRONG KB answer.
    """
    if not qa_list:
        return {"q": "", "a": "", "weak_match": False}
    best_match = max(qa_list, key=lambda qa: similarity(query, qa['q']))
    sim_score = similarity(query, best_match['q'])
    if sim_score < weak_threshold:
        # No KB info, no topic match (totally out-of-scope)
        return {"q": "", "a": "", "weak_match": False}
    elif sim_score < threshold:
        # General/topic match, but not specific – signal weak_match
        return {"q": best_match['q'], "a": "", "weak_match": True}
    return {"q": best_match['q'], "a": best_match['a'], "weak_match": False}


def clean_gemini_output(text: str) -> str:
    """
    Removes leading/trailing meta, KB source, or disclaimer information from Gemini output.
    Ensures only direct answers are delivered to the user.
    """
    import re
    META_PATTERNS = [
        # Remove variants at start of the answer
        r"(?i)^ *(?:based on (?:the )?(?:provided )?(?:knowledge ?base|context|sources)[^:]*:?)",
        r"(?i)^(?:as an?\s+[^\\s:,]+ [^\\s:,]+,?)[\\s:.-]*",
        r"(?i)^ *(?:this information[^:]*:?)",
        r"(?i)^ *(?:note:)[^\n\r]*",
        r"(?i)^ *(?:please note)[^\n\r]*",
        r"(?i)^ *(?:source[sd]?:)[^\n\r]*",
        r"(?i)^ *(?:from the knowledge base[^:]*:?)",
        r"(?i)^ *(?:provided context[^:]*:?)",
        r"(?i)^\(?(?:based on|as an ai language model|this information|provided context)[^\)]*\)?",
    ]
    # Remove trailing variants
    TRAIL_PATTERNS = [
        r"(?i)\(? *(?:based on (?:the )?(?:provided )?(?:knowledge ?base|context|sources)[^)]*)\)?[.!]? *$",
        r"(?i)\(? *(?:from the knowledge base)[^)]*\)?[.!]? *$",
        r"(?i)\(? *(?:provided context)[^)]*\)?[.!]? *$",
    ]
    clean_text = text
    for pat in META_PATTERNS:
        clean_text = re.sub(pat, "", clean_text, flags=re.IGNORECASE | re.MULTILINE)
    for pat in TRAIL_PATTERNS:
        clean_text = re.sub(pat, "", clean_text, flags=re.IGNORECASE | re.MULTILINE)
    clean_text = clean_text.strip()
    return clean_text


# PUBLIC_INTERFACE
def get_gemini_response(query: str, rag_answer: str, memory: ConversationBufferMemory) -> str:
    """
    Enhance the answer using Google Gemini API, considering the chat context.
    Never include statements about sources, knowledge base, RAG, or meta-assertions in the prompt or response.
    """
    mem_str = memory.buffer_as_str if hasattr(memory, "buffer_as_str") else ""
    prompt = (
        f"You are an expert software assistant.\n"
        f"User's question: '{query}'\n"
        f"{f'Relevant answer: \"{rag_answer}\"\n' if rag_answer.strip() else ''}"
        f"Conversation history:\n{mem_str}\n"
        f"Please answer the user's latest question. Be concise and clear."
    )

    # Support container_env naming with fallback
    gemini_api_key = os.getenv("REACT_APP_GEMINI_API_KEY") or os.getenv("GEMINI_API_KEY")
    if not gemini_api_key:
        raise HTTPException(status_code=500, detail="Gemini API key is not set in environment variables.")
    try:
        genai.configure(api_key=gemini_api_key)
        model = genai.GenerativeModel("gemini-2.5-flash")
        response = model.generate_content([{"role": "user", "parts": [prompt]}])
        raw_answer = response.text.strip()
        return clean_gemini_output(raw_answer)
    except Exception as e:
        # Fallback to original RAG answer if Gemini API fails
        return clean_gemini_output(f"[Gemini enhancement unavailable: {e}]\n{rag_answer}")


# Ensure tables exist on startup
create_tables()

# Load the knowledge base at startup
ANSWERS_PATH = os.path.join(os.path.dirname(__file__), "answers.txt")
QA_LIST = load_answers(ANSWERS_PATH)


@app.get("/", tags=["Health"])
def health_check():
    """
    PUBLIC_INTERFACE
    API health check endpoint.

    Returns:
        dict: Status message.
    """
    return {"message": "Healthy"}


@app.post(
    "/chat",
    response_model=ChatResponse,
    tags=["Chat"],
    summary="Chat with bot",
    description="Submit a chat query. Gemini always answers; a RAG knowledge base document is included as additional Gemini context if relevant; conversation history is always provided to Gemini for context."
)
def chat(request: ChatRequest, db=Depends(get_db)):
    """
    PUBLIC_INTERFACE
    Handles user's chat request. All answers come directly from Gemini.
    The current conversation history is always provided to Gemini to support follow-up queries or context-aware answers.
    """
    import traceback

    def _safe_str_output(val, fallback=""):
        if val is None or (isinstance(val, str) and val.strip() == ""):
            return fallback
        return str(val)

    try:
        session_id = request.session_id
        if not session_id or not isinstance(session_id, str):
            raise HTTPException(status_code=400, detail="session_id must be a non-empty string.")

        # Ensure in-memory context exists and hydrate it from DB if it's new/empty
        if session_id not in CONVERSATION_MEMORY:
            CONVERSATION_MEMORY[session_id] = ConversationBufferMemory(
                return_messages=True,
                output_key="output"
            )
        memory = CONVERSATION_MEMORY[session_id]

        try:
            msgs = getattr(memory, "chat_memory").messages if hasattr(memory, "chat_memory") else []
            if not msgs:
                # Hydrate memory from DB history (pair user->assistant turns)
                db_msgs = get_messages_for_session(db, session_id=session_id, limit=100)
                last_user = None
                for m in db_msgs:
                    role = (m.get("role") or "").lower()
                    content = (m.get("content") or "")
                    if role == "user":
                        last_user = content
                    elif role == "assistant":
                        if last_user is not None:
                            memory.save_context({"input": last_user}, {"output": content})
                            last_user = None
                # If trailing user message without assistant, store with placeholder so context retains it
                if last_user is not None:
                    memory.save_context({"input": last_user}, {"output": "No answer available"})
        except Exception:
            # Do not hard fail; proceed even if hydration fails
            pass

        # Ensure a conversation exists in DB
        convo = get_or_create_conversation(db, session_id=session_id, user_id=None, title=None)

        # Persist the user message to DB (no placeholder memory write)
        create_message(db, conversation_id=convo.id, role="user", content=_safe_str_output(request.query))

        # RAG retrieval
        qa = rag_retrieve(request.query, QA_LIST)
        rag_weak_match = qa.get("weak_match", False)
        kb_q = qa.get("q", "")
        kb_a = qa.get("a", "")
        if kb_a != "":
            rag_answer = kb_a
        elif kb_q != "" and rag_weak_match:
            rag_answer = ""
        else:
            rag_answer = ""

        # Compose Gemini answer (context from hydrated memory; current input is passed explicitly)
        try:
            gemini_answer = get_gemini_response(request.query, rag_answer, memory)
        except Exception as e:
            gemini_answer = "[Gemini unavailable: {}]\n{}".format(e, rag_answer or "")

        # Final output cleaning for defense-in-depth
        gemini_answer = clean_gemini_output(_safe_str_output(gemini_answer, ""))

        # Save the final turn to memory and DB (single, consistent write)
        try:
            memory.save_context({"input": request.query}, {"output": gemini_answer})
        except Exception:
            # Memory write errors should not break the request
            pass

        try:
            create_message(db, conversation_id=convo.id, role="assistant", content=gemini_answer)
        except Exception:
            # DB write error for assistant shouldn't break the request if user message already persisted
            pass

        # Prepare conversation history for output (last 20 messages) from DB
        conversation_history: List[dict] = []
        try:
            history = get_messages_for_session(db, session_id=session_id, limit=20)
            for m in history:
                role = (m.get("role") or "").lower()
                content = _safe_str_output(m.get("content"))
                msg_type = "ai" if role == "assistant" else "human"
                conversation_history.append(
                    {"type": msg_type, "content": content}
                )
        except Exception:
            # Fallback to memory if DB history fails
            if hasattr(memory, "chat_memory") and hasattr(memory.chat_memory, "messages"):
                for m in memory.chat_memory.messages[-20:]:
                    m_dict = {}
                    if hasattr(m, "type") and hasattr(m, "content"):
                        m_dict = {"type": m.type, "content": _safe_str_output(m.content)}
                    conversation_history.append(m_dict)

        return ChatResponse(
            rag_answer=_safe_str_output(rag_answer),  # Could be empty str
            gemini_answer=gemini_answer,              # Gemini's answer, cleaned of meta/source
            conversation_history=conversation_history
        )

    except HTTPException:
        raise  # Allow FastAPI HTTPExceptions to propagate
    except Exception as e:
        tb = traceback.format_exc()
        print(f"Internal Server Error in /chat endpoint: {e}\nTraceback:\n{tb}")
        raise HTTPException(status_code=500, detail=f"Internal Server Error: {e}")


# PUBLIC_INTERFACE
@app.post(
    "/register",
    response_model=RegisterResponse,
    tags=["UserAuth"],
    summary="Register a new user",
    description="Endpoint for user registration using username, email, and password. Returns user details on success. Username and email must be unique.",
    responses={
        409: {"description": "Username/email already registered"},
        400: {"description": "Validation error"},
    },
)
def register(request: RegisterRequest, db=Depends(get_db)):
    """
    PUBLIC_INTERFACE
    Registers a new user, stores credentials securely in the database.

    Args:
        request (RegisterRequest): The registration data (username, email, password).
        db (Session): SQLAlchemy Session dependency.

    Returns:
        RegisterResponse: id, username, and email of the registered user.

    Raises:
        HTTPException: If username or email already exists, or validation fails.
    """
    try:
        user = create_user(db, username=request.username, email=request.email, password=request.password)
    except ValueError as e:
        raise HTTPException(status_code=409, detail=str(e))
    return RegisterResponse(id=user.id, username=user.username, email=user.email)


# PUBLIC_INTERFACE
@app.post(
    "/login",
    response_model=LoginResponse,
    tags=["UserAuth"],
    summary="User login",
    description="Endpoint for users to login with username and password.",
    responses={
        401: {"description": "Incorrect username or password"},
        400: {"description": "Validation error"},
    },
)
def login(request: LoginRequest, db=Depends(get_db)):
    """
    PUBLIC_INTERFACE
    Authenticate a user's credentials and return basic user info.

    Args:
        request (LoginRequest): Login data (username, password).
        db (Session): SQLAlchemy Session dependency.

    Returns:
        LoginResponse: id, username, and email of the authenticated user.

    Raises:
        HTTPException: If credentials are invalid.
    """
    user = get_user_by_username(db, request.username)
    if not user or not verify_password(request.password, user.hashed_password):
        raise HTTPException(status_code=401, detail="Incorrect username or password")
    return LoginResponse(id=user.id, username=user.username, email=user.email)


# PUBLIC_INTERFACE
@app.get(
    "/chat/history/{session_id}",
    tags=["Chat"],
    summary="Get chat history for a session",
    description="Return chronological chat messages for the specified session.",
    response_model=List[HistoryItem],
)
def chat_history(session_id: str, db=Depends(get_db)):
    """
    PUBLIC_INTERFACE
    Retrieve chat history for a given session_id from the database.

    Args:
        session_id (str): The session identifier for the conversation.
        db (Session): SQLAlchemy Session dependency.

    Returns:
        List[HistoryItem]: List of messages mapped to 'human' (user) and 'ai' (assistant) with timestamps.
    """
    if not session_id or not isinstance(session_id, str):
        raise HTTPException(status_code=400, detail="session_id must be a non-empty string.")
    rows = get_messages_for_session(db, session_id=session_id, limit=100)
    history: List[HistoryItem] = []
    for m in rows:
        role = (m.get("role") or "").lower()
        msg_type = "ai" if role == "assistant" else "human"
        content = str(m.get("content") or "")
        history.append(HistoryItem(type=msg_type, content=content, created_at=m.get("created_at")))
    return history


# PUBLIC_INTERFACE
@app.post(
    "/chat/session/attach",
    tags=["Chat"],
    response_model=ConversationInfo,
    summary="Attach a session to a user",
    description="Bind an existing or new conversation (by session_id) to a specific user so their chat sessions are associated with their account. Optionally provide a title to set if one isn't already set.",
    responses={
        404: {"description": "User not found"},
        400: {"description": "Validation error"},
    },
)
def attach_session(request: AttachSessionRequest, db=Depends(get_db)):
    """
    PUBLIC_INTERFACE
    Attach a conversation identified by session_id to a user account.

    Args:
        request (AttachSessionRequest): session_id, username, optional title.
        db (Session): SQLAlchemy Session dependency.

    Returns:
        ConversationInfo: The conversation metadata after binding.
    """
    if not request.session_id.strip():
        raise HTTPException(status_code=400, detail="session_id must be a non-empty string.")
    user = get_user_by_username(db, request.username)
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
    convo = attach_session_to_user(db, session_id=request.session_id, user_id=user.id, title=request.title)
    return ConversationInfo(id=convo.id, session_id=convo.session_id, title=convo.title, created_at=convo.created_at.isoformat() if convo.created_at else None)


# PUBLIC_INTERFACE
@app.get(
    "/conversations/{username}",
    tags=["Chat"],
    response_model=List[ConversationInfo],
    summary="List conversations for a user",
    description="Return the list of conversations associated with the given username, ordered by most recent.",
    responses={
        404: {"description": "User not found"},
        400: {"description": "Validation error"},
    },
)
def list_conversations(username: str, db=Depends(get_db)):
    """
    PUBLIC_INTERFACE
    List a user's conversations.

    Args:
        username (str): Username whose conversations are requested.
        db (Session): SQLAlchemy Session dependency.

    Returns:
        List[ConversationInfo]: Conversations with id, session_id, title, created_at.
    """
    if not username or not isinstance(username, str):
        raise HTTPException(status_code=400, detail="username must be a non-empty string.")
    user = get_user_by_username(db, username)
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
    rows = get_conversations_for_user(db, user_id=user.id, limit=100)
    return [
        ConversationInfo(
            id=r["id"],
            session_id=r["session_id"],
            title=r["title"],
            created_at=r["created_at"],
        )
        for r in rows
    ]


# Add endpoint doc for WebSocket and real-time (optional, can expand later)
@app.get("/chat/wsinfo", tags=["Chat"], summary="WebSocket usage info", description="Info about WebSocket/API support for real-time chat.")
def chat_wsinfo():
    """
    PUBLIC_INTERFACE
    Returns information about real-time chat support (WebSocket or usual polling).
    """
    return {"detail": "Current version supports REST API chat only. Real-time WebSocket may be added in future versions."}
