import os
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from typing import List
import google.generativeai as genai

from dotenv import load_dotenv
from langchain.memory import ConversationBufferMemory

# Load environment variables
load_dotenv()

# Memory store for chat contexts (keyed by session_id).
CONVERSATION_MEMORY = {}

app = FastAPI(
    title="IntelliQuery Chatbot API",
    version="1.0.0",
    description="FastAPI backend for the IntelliQuery chatbot, providing chat endpoints using RAG from answers.txt, Google Gemini API, and context tracking."
)

openapi_tags = [
    {"name": "Health", "description": "Health check endpoint."},
    {"name": "Chat", "description": "Endpoints for chat, response retrieval, and context management."}
]

# Allow CORS from everywhere for demo/dev
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class ChatRequest(BaseModel):
    """Schema for a chat request."""
    session_id: str = Field(..., description="Unique session identifier for the conversation context.")
    query: str = Field(..., description="User's query (question or message).")

class ChatResponse(BaseModel):
    """Schema for the chat response."""
    rag_answer: str = Field(..., description="Retrieved answer from the RAG knowledge base.")
    gemini_answer: str = Field(..., description="Enhanced answer generated by Gemini API.")
    conversation_history: List[dict] = Field(..., description="Full chat context for this session.")

def load_answers(filepath: str) -> List[dict]:
    """Load questions and answers from the answers.txt file as a list of dicts ([{'q': ..., 'a': ...}, ...])."""
    qa_list = []
    with open(filepath, encoding='utf-8') as f:
        lines = f.readlines()
    q, a = None, None
    for line in lines:
        line = line.strip()
        if line.startswith("Q:"):
            q = line[2:].strip()
        elif line.startswith("A:"):
            a = line[2:].strip()
            if q is not None and a is not None:
                qa_list.append({'q': q, 'a': a})
                q, a = None, None
    return qa_list

def similarity(a: str, b: str) -> float:
    """Simple similarity score based on token overlap (lower resource fallback for semantic matching)."""
    set_a, set_b = set(a.lower().split()), set(b.lower().split())
    shared = set_a.intersection(set_b)
    if not set_a or not set_b:
        return 0.0
    return len(shared) / max(len(set_a), len(set_b))

def rag_retrieve(query: str, qa_list: List[dict]) -> dict:
    """Retrieve the QA pair most relevant to the query."""
    best_match = max(qa_list, key=lambda qa: similarity(query, qa['q']))
    return best_match

def get_gemini_response(query: str, rag_answer: str, memory: ConversationBufferMemory) -> str:
    """
    PUBLIC_INTERFACE
    Enhance the RAG answer using Google Gemini API, considering the chat context.
    """
    # Prepare the prompt
    mem_str = memory.buffer_as_str if hasattr(memory, "buffer_as_str") else ""
    prompt = (
        f"You are an expert software assistant. The user asked: '{query}'\n"
        f"Most relevant knowledge base answer: \"{rag_answer}\"\n"
        f"Conversation context: {mem_str}\n"
        f"Please provide the clearest and most helpful answer based on all of the above."
    )

    # Call Gemini API
    gemini_api_key = os.getenv("GEMINI_API_KEY", "")
    if not gemini_api_key:
        raise HTTPException(status_code=500, detail="Gemini API key is not set in environment variables.")
    try:
        genai.configure(api_key=gemini_api_key)
        model = genai.GenerativeModel("gemini-pro")
        response = model.generate_content([{"role": "user", "parts": [prompt]}])
        answer = response.text.strip()
        return answer
    except Exception as e:
        # Fallback to original RAG answer if Gemini API fails
        return f"[Gemini enhancement unavailable: {e}]\nKnowledge base answer: {rag_answer}"

# Load the knowledge base at startup
ANSWERS_PATH = os.path.join(os.path.dirname(__file__), "answers.txt")
QA_LIST = load_answers(ANSWERS_PATH)

@app.get("/", tags=["Health"])
def health_check():
    """
    PUBLIC_INTERFACE
    API health check endpoint.

    Returns:
        dict: Status message.
    """
    return {"message": "Healthy"}

@app.post("/chat", response_model=ChatResponse, tags=["Chat"], summary="Chat with bot", description="Submit a chat query. Retrieves an answer from the RAG knowledge base, enhances with Gemini, and returns the chat context.")
def chat(request: ChatRequest):
    """
    PUBLIC_INTERFACE
    Handles a user's chat request, uses RAG to get initial answer, calls Gemini API for enhanced answer,
    and maintains conversation context using ConversationBufferMemory.

    Args:
        request (ChatRequest): Contains session_id and user query.
    Returns:
        ChatResponse: RAG answer, Gemini-enhanced answer, and conversation context.
    """
    # Handle conversation memory
    session_id = request.session_id
    if session_id not in CONVERSATION_MEMORY:
        CONVERSATION_MEMORY[session_id] = ConversationBufferMemory(return_messages=True)
    memory = CONVERSATION_MEMORY[session_id]

    # Add user input to memory
    memory.save_context({"input": request.query}, {})

    # RAG: Retrieve best match
    qa = rag_retrieve(request.query, QA_LIST)
    rag_answer = qa["a"]

    # Add bot's answer to memory before Gemini call
    memory.save_context({}, {"output": rag_answer})

    # Enhance answer with Gemini
    gemini_answer = get_gemini_response(request.query, rag_answer, memory)

    # Add Gemini-enhanced answer to memory
    memory.save_context({}, {"output": gemini_answer})

    # Prepare conversation history (latest 10 exchanges)
    conversation_history = []
    if hasattr(memory, "chat_memory") and hasattr(memory.chat_memory, "messages"):
        for m in memory.chat_memory.messages[-20:]:
            m_dict = {}
            if hasattr(m, "type") and hasattr(m, "content"):
                m_dict = {"type": m.type, "content": m.content}
            conversation_history.append(m_dict)

    return ChatResponse(
        rag_answer=rag_answer,
        gemini_answer=gemini_answer,
        conversation_history=conversation_history,
    )

# Add endpoint doc for WebSocket and real-time (optional, can expand later)
@app.get("/chat/wsinfo", tags=["Chat"], summary="WebSocket usage info", description="Info about WebSocket/API support for real-time chat.")
def chat_wsinfo():
    """
    PUBLIC_INTERFACE
    Returns information about real-time chat support (WebSocket or usual polling).
    """
    return {"detail": "Current version supports REST API chat only. Real-time WebSocket may be added in future versions."}
